project:
  type: book

book:
  title: "Python Course"
  subtitle: "A friendly, hands-on introduction to Python"
  author: "Fabrizio Damicelli"
  site-url: "https://fabridamicelli.github.io/python-course"
  favicon: ./favicon.svg
  sharing:
    - "twitter"
    - "linkedin"
    - "facebook"
  navbar:
    left:
      - href: https://fabridamicelli.github.io
        text: Author's Website
        icon: person-video
    right:
      - href: https://github.com/fabridamicelli/python-course?tab=readme-ov-file#support
        text: Star this Course
        icon: star-fill
      - href: https://www.youtube.com/@fabridamicelli
        text: Python Videos
        icon: youtube
      - href: https://github.com/fabridamicelli
        icon: github
      - href: https://x.com/fabridamicelli
        icon: twitter-x
      - href: https://linkedin.com/in/fabridamicelli
        icon: linkedin

  chapters:
    - index.qmd
    - 01_1_getting_started.ipynb
    - 01_2_executing_code.ipynb
    - 02_types_data_structures.ipynb
    - 03_1_flow_control.ipynb
    - 04_functions.ipynb
    # - 041_scope.ipynb
    - 05_comprehensions.ipynb
    - lab_builtin_for_the_win.ipynb
    - 06_imports.ipynb
    - 062_read_and_write.ipynb
    - 061_dependencies.ipynb
    - 063_common_data_formats.ipynb
    - 111_debugging.ipynb
    - 08_numpy.ipynb
    - 081_pandas.ipynb
    - 09_plotting.ipynb
    - lab_explore_data.ipynb
    # - 11_cli.ipynb
    - 03_2_error_handling.ipynb
    - 051_oop.ipynb
    - 10_testing.ipynb
    # - 13_tools.ipynb
    - notebook_workflow.ipynb
    - 999_glossary.ipynb
    - references.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    highlight-style: breeze
    include-in-header: ../plausible.html
